impresso/impresso-frontend

src/App.vue
src/components/TheHeader.vue

Removed all the internal component styling and rewritten the html to use (Vue)Bootstrap

refactor TheHeader component

---

src/components/IssuePage.vue
src/components/modules/IssueViewer.vue

removed all custom styling except layout and made some markup a bit simpler

refactored issuepage

---

package-lock.json
package.json
src/main.js

make sure to npm-install because we have new packages

replaced bootstrap with bootpresso custom impresso-bootstrap theme

---

config/dev.env.js
config/prod.env.js
package-lock.json
src/App.vue
src/components/CollectionTagger.vue
src/components/IssuePage.vue
src/components/NamedEntityExplorer.vue
src/components/SearchResultsListItem.vue
src/components/SearchResultsPage.vue
src/components/SearchResultsTilesItem.vue
src/components/modules/CollectionSidebarItem.vue
src/components/modules/IssueViewer.vue
src/components/modules/IssueViewerZoomSlider.vue
src/components/modules/NamedEntityExplorerDateSlider.vue
src/components/modules/ThumbnailSlider.vue
src/main.js

removing local stylesheet overrides,
replaced typekit ID

prepare frontend for impresso-theme

---

src/components/d3/Skyline.vue

y-axis start from 0;

---

src/components/modules/FilterNamedEntity.vue
src/components/modules/FilterSettingContext.vue
src/components/modules/FilterSettingPrecision.vue
src/components/modules/FilterString.vue
src/components/modules/FilterWrapper.vue
src/models/Contexts.js
src/models/FilterString.js
src/models/Precisions.js

String filter now accepts a 'precision'. Also the filters are divided into smaller components for better codereuse.
NOTE: The precision is not yet supported by the MiddelLayer

better filter components

---

src/components/IssuePage.vue
src/components/modules/OpenSeadragonViewer.vue

Reverts impresso/impresso-frontend#111

Revert "added region click event and styling"

---

src/store/Issue.js

page from middle layer api now complies to frontend model

---

src/components/Autocomplete.vue
src/components/SearchFacets.vue
src/components/SearchFilters.vue
src/components/SearchPage.vue
src/components/modules/FacetLanguage.vue
src/components/modules/FacetNewspaper.vue
src/components/modules/FacetTopic.vue
src/components/modules/FilterLanguage.vue
src/components/modules/FilterNewspaper.vue
src/components/modules/FilterTopic.vue
src/i18n/messages.js
src/models/FilterFactory.js
src/models/FilterLanguage.js
src/models/FilterNewspaper.js
src/models/FilterTopic.js
src/models/SuggestionFactory.js
src/models/SuggestionTopic.js
src/models/Topic.js
src/models/TopicWord.js
src/store/Search.js

Facets are now a list of buttons. On click event a filter is created.

rewrite of the facet to filter mechanism

---

src/components/Autocomplete.vue
src/models/SuggestionFactory.js

no autocomplete suggestions for type location or type person where shown because autocomplete endpoint changed type mention to type entity

bugfix: autocomplete type mention changed to entity

---

config/dev.env.js
src/App.vue

only show tawk.to on the prod server, not on local dev

added conditional to env file for tawkto

---

src/App.vue
src/components/TheHeader.vue
src/router/index.js

added navguard on logout router for logout, instead of calling the logout store action from the header component

logout via navguard

---

src/main.js
src/services/index.js

sorry guys, third time's a charm...

added prefetch before creation of vue app to ensure user authenticate has been called

---

src/components/IssuePage.vue
src/components/modules/IssueViewerText.vue
src/components/modules/TableOfContents.vue
src/models/Region.js
src/store/Issue.js

fallback to first article of page if no article uid is specified

single article in text view

---

src/components/modules/CollectionAddTo.vue
src/components/modules/CollectionList.vue

removed countEntities for first release,
see this issue: https://github.com/impresso/impresso-frontend/issues/184#issuecomment-464621721
please undo this commit when service is ready.

commented collection item count out

---

src/components/modules/FilterWrapper.vue

solved this issue: 
https://github.com/impresso/impresso-frontend/issues/184#issuecomment-465957050

applied max-width to filter wrapper

---

src/components/CollectionDetailPage.vue
src/store/Collections.js

see https://github.com/impresso/impresso-middle-layer/issues/93#issuecomment-465965356 for specs

prepared Collection page for sorting

---

package.json
src/filters/markdown.js

https://www.npmjs.com/package/markdown-it-decorate

added markdown-decorate for classes in md, and enabled html in md

---

src/components/modules/FilterWrapper.vue

https://github.com/impresso/impresso-frontend/issues/250

fixed filter-pill bug with firefox (issue #250)

---

src/components/IssuePage.vue
src/components/modules/CollectionAddTo.vue

- removed some obsolete code in CollectionAddTo component
- removed pagination and centered displayAs toggle on IssueViewer
- replaced text label with icons for toggle on IssueViewer

minor improvements

---

src/components/TheHeader.vue
src/components/modules/Toast.vue
src/services/index.js
src/store/Jobs.js
src/store/index.js

toast component may be used as user friendly notifications for any background tasks.
this pull-request also includes a test button

created toast component and jobs service

---

src/components/modules/ThumbnailSlider.vue
src/components/modules/ThumbnailSliderItem.vue

zindex 1000 is reserved for dropdowns

fixed high zindex on thumbnail slider

---

src/components/SearchPage.vue
src/components/TheHeader.vue
src/store/Jobs.js

Save / Export dropdown is now only available to logged users

Fix/issue #285 jobs.find service throws exception when not logged

---

src/components/UserLoginPage.vue
src/router/index.js

Expected behaviour after login is to get back to requested page, not home page

redirect users to referrer path on login

---

src/components/modules/ThumbnailSlider.vue

added check for page type on watcher, so we only slide to page if there is actually a page change

fix thumbnail slider errer

---

src/components/modules/FilterFacetBucket.vue
src/i18n/messages.js

fix collection names

---

src/components/IssuePage.vue
src/components/SearchImagesPage.vue

makes the IMAGES tab active on the issuepage when url has ?tab=images

---

src/components/Autocomplete.vue

https://github.com/impresso/impresso-frontend/issues/319

clear input value after submit

---

src/components/SearchPage.vue
src/components/TheHeader.vue
src/components/modules/CollectionAddTo.vue
src/components/modules/CollectionAddToList.vue

added option to save selected items 
https://github.com/impresso/impresso-frontend/issues/318#issue-445854334

Save/export dropdown #328

---

src/components/Autocomplete.vue

pressing Enter on initialSuggestions should trigger submitInitialSuggestion()

fixed bug with keyboard/Enter

---

src/components/SearchPage.vue
src/store/Search.js

I added a separate Mutation `EXPORT_FROM_UIDS` it may be double emploi, but at this point, I do not wish to break another function `EXPORT_FROM_QUERY`

added export selection items

---

src/components/Autocomplete.vue

fixed issue where search failed when not using autocomplete (search button / enter key on search box)

fixed issue with keyboard and search button

---

src/assets/homepage.json
src/components/HomePage.vue
src/components/HomePageFaq.vue
src/components/HomePageFooter.vue
src/components/HomePageMessages.vue
src/components/HomePageRecipes.vue
src/components/HomePageSplash.vue

- addd message to homepage informing user to sign nda to get full access to the corpus
- added button to close a message , which is then added to localstorage and won't show up again

added message to homepage and close method

---

src/App.vue
src/components/Autocomplete.vue
src/components/Explorer.vue
src/components/SearchFacets.vue
src/components/SearchPage.vue
src/components/modules/FacetExplorer.vue
src/components/modules/FilterMonitor.vue
src/components/modules/SearchResultsSummary.vue
src/i18n/messages.js
src/models/Entity.js
src/models/Topic.js
src/store/Buckets.js
src/store/Explorer.js
src/store/index.js

This PR fixes a few UX issues (#438) and clean up the autocomplete structure. TO be tested, as the autocomplete behaviour looks weird, this is probably due to my use of computed property `suggestionIndex`. Can you check?

fix autocomplete and resolve facet explorer / explorer ambiguity

---

src/assets/homepage.json

Subject: impresso account request
Body: Please provide your contact details (name and if relevant, institutional affiliation) and planned use of the impresso collection.

Added link to info@impresso-project.ch

---

package-lock.json
package.json
src/App.vue
src/assets/disclaimer.json
src/components/LegalPage.vue
src/components/TheHeader.vue
src/components/modals/DisclaimerNotice.vue
src/i18n/messages.js
src/router/index.js
src/store/Settings.js
src/store/index.js

added disclaimer pull-up and blank page
issue #473

Feature/legal disclaimer (issue #473)

---

src/App.vue
src/components/modals/DisclaimerNotice.vue
src/components/modules/FilterImageUpload.vue
src/i18n/messages.js
src/services/index.js
src/store/Settings.js

Debug image upload

---

src/components/SearchPage.vue

also fixed a bug where these actions were available for non logged users

UX: group select all checkbox with selection actions

---

src/App.vue
src/components/SearchPage.vue
src/components/SearchPills.vue
src/components/SearchQueriesComparisonPage.vue
src/components/modules/searchQueriesComparison/FacetOverviewPanel.vue
src/components/modules/searchQueriesComparison/QueryHeaderPanel.vue

Style/compare page - follows PR improved search pills

---

src/App.vue
src/components/TheHeader.vue
src/i18n/messages.js
src/main.js
src/services/index.js
src/store/Jobs.js
src/store/index.js

yet another PR for error handling, still incomplete, but a lot more robust. Now error messages are queued and there are more info about which part of the app throws the exception.

Improve errors handling

---

src/assets/faqpage.json

https://github.com/impresso/impresso-frontend/issues/554
and
https://github.com/impresso/impresso-frontend/issues/555

rearranged faq according to suggestions 

---

src/App.vue
src/components/Monitor.vue
src/components/SearchPage.vue
src/components/TheHeader.vue
src/components/modules/SearchQuerySummary.vue
src/components/modules/SearchTabs.vue
src/components/modules/tooltips/TopicsExplorerTooltip.vue
src/models/SearchQuery.js
src/store/Monitor.js
src/store/Search.js
src/store/SearchQueryExplorer.js
src/store/Topics.js
src/store/index.js

- topic: fix #601 and #595 to add/exclude topic to current search
- summary component for humans: fix #615 
- add currrent search filters in the header

Misc bug fix

---

src/components/Monitor.vue

add "loading..." and leave a fix space for the timeline to avoid glitches

fix layout

---

package-lock.json
package.json
src/components/Explorer.vue
src/components/SearchPills.vue
src/components/TextReuseClustersPage.vue
src/components/TheHeader.vue
src/components/modules/FacetExplorer.vue
src/components/modules/FilterDateRange.vue
src/components/modules/FilterMonitor.vue
src/components/modules/FilterNumberRange.vue
src/components/modules/RangeFacetExplorer.vue
src/components/modules/lists/ItemLabel.vue
src/components/modules/textReuse/ClustersSearchPanel.vue
src/logic/filters.js
src/models/models.d.ts
src/services/index.js

Also includes new type of filters: range.

Filter text reuse clusters

---

src/components/IssuePage.vue

stopped arrow key events from issue viewer from interfering with any other component (e.g. autocomplete)

kill keyboard events with component

---

src/models/SearchQuery.js

Fix for https://github.com/impresso/impresso-frontend/issues/793

Missing items 

---

src/components/SearchQueriesComparisonPage.vue
src/components/modules/searchQueriesComparison/QueryHeaderPanel.vue

Fixes https://github.com/impresso/impresso-frontend/issues/792

Remove queries that have 0 filters.

---

package-lock.json
package.json
src/components/SearchFacets.vue
src/components/SearchImagesPage.vue
src/components/SearchNgramsPage.vue
src/components/SearchPage.vue
src/components/SearchPills.vue
src/components/SearchQueriesComparisonPage.vue
src/components/modules/SearchSidebar.vue
src/d3-modules/Line.js
src/d3-modules/LineChart.js
src/logic/facets.js
src/logic/filters.js
src/models/Bucket.js
src/models/FilterFactory.js
src/models/FilterTopic.js
src/models/SearchQuery.js
src/models/Topic.js
src/models/index.d.ts
src/pages/PowerUserVisualisation.vue
src/plugins/Helpers.js
src/router/index.js
src/router/util.js
src/services/index.js
src/vue-shims.d.ts
test/spec/logic/filters.spec.js
tsconfig.json

Power user visualisation is still a work in progress but several changes to filters make it worthwhile to merge it before completion. The power user page (`powervis`) is not linked from everywhere yet.
This PR also fixes https://github.com/impresso/impresso-frontend/issues/761.

Power user visualisation. Part 1.

---

src/components/modules/FilterDateRange.vue

update range only on valid dates

---

src/logic/queryParams.js
src/router/util.js

add f as first step

---

src/App.vue

- remove square border applied to checkboxes (does not look good on switches)

update checkbox style for switches

---

src/logic/queryParams.js

Migrating legacy query parameter `f` instead of reading it. Reasoning is described here: https://github.com/impresso/impresso-frontend/issues/825#issuecomment-623384949

Migrating legacy filters parameter.

---

src/components/SearchPills.vue
src/components/modules/FilterDateRange.vue
src/components/modules/SearchQuerySummary.vue
src/i18n/dateTimeFormats.js

Fix for https://github.com/impresso/impresso-frontend/issues/819

Use UTC where date range is displayed

---

src/logic/user.js
src/pages/UserRegister.vue

- add alert for feathers errors
- add styling to fields with errors

improve validation

---

src/logic/queryParams.js
src/router/index.js

Fix for https://github.com/impresso/impresso-frontend/issues/860

Updating query parameter on next tick when `$navigation` mixin is available

---

src/components/Explorer.vue
src/components/SearchQueriesComparisonPage.vue
src/components/TextReuseClustersPage.vue
src/main.js
src/models/index.d.ts

Also setting default tab in "I&C" to Inspect.

Display first text reuse cluster if none were selected.

---

src/components/Explorer.vue
src/components/modules/FacetExplorer.vue
src/pages/SearchImages.vue

fix styling inconsistency

---

src/components/Autocomplete.vue
src/i18n/messages.js
src/store/Autocomplete.js

the first commits are small UX improvements with autocomplete
#894 : in the commits from today, I added the separate call to collection service and add them to the suggestions.

Gain perf on autocomplete #894

---

src/pages/SearchNgrams.vue

Fix unigram tooltip

---

package-lock.json
package.json
src/App.vue
src/components/Autocomplete.vue
src/components/TopicsExplorerPage.vue
src/components/TopicsPage.vue
src/components/modules/tooltips/Tooltip.vue
src/components/modules/tooltips/TopicsExplorerTooltip.vue
src/d3-modules/Dimension.js
src/d3-modules/Graph.js
src/i18n/messages.js
src/models/Entity.js
src/store/Topics.js

* Topics graph.
* Autocomplete fix for not logged in users.

Release 2.6.0

---

src/App.vue
src/components/SearchPills.vue
src/components/modules/EntitiesSuggestionsList.vue
src/components/modules/FilterMonitor.vue
src/i18n/messages.js

I messed quite a bit with the `entitiesSuggestionList` ... please check it out. 
I tried out **viz-bars** but it looked a bit overkill. also, _countMentions_ and _countItems_ return the same number most of the time. just left it as text only for now.

Interface elements

---

src/components/TestPage.vue
src/components/modules/vis/TimePunchcardChart.vue
src/d3-modules/TimePunchcardChart.js

Punchcard time chart for entities comparison page.

Punchcard time chart

---

src/components/modules/vis/TimePunchcardChart.vue
src/d3-modules/TimePunchcardChart.js

- fixed a bug with major/minor ticks (fix)
- enlarged maximum size circle highlight (ux)

Entity timeline > Fix major ticks

---

src/components/modules/SearchQuerySummary.vue

just noticed that year was not in summary so i added it

Summary add year and typo

---

src/components/Autocomplete.vue
src/components/SearchPills.vue
src/components/modules/SearchSidebar.vue
src/components/modules/textReuse/ClustersSearchPanel.vue
src/pages/Search.vue

enhanced <search-pills> with reset button

---

src/pages/SearchNgrams.vue

Implementation of https://github.com/impresso/impresso-frontend/issues/904

add similar words

---

src/components/EntitiesExplorerPage.vue
src/components/TopicsPage.vue
src/components/modals/SearchQueryExplorer.vue
src/logic/filters.js
src/pages/Search.vue
src/pages/SearchQueriesComparison.vue

Fix for https://github.com/impresso/impresso-frontend/issues/963

Fixed incompatible filter types

---

src/components/modules/CollectionList.vue
src/store/Collections.js

Fixes https://github.com/impresso/impresso-frontend/issues/965

display a user friendly error when an existing label is used for a new collection

---

package-lock.json
package.json
src/components/CollectionDetailPage.vue
src/components/IssuePage.vue
src/components/modals/CopyToClipboard.vue
src/components/modals/SearchQueryExplorer.vue
src/components/modules/IssueViewerText.vue
src/components/modules/SearchResultsListItem.vue
src/components/modules/SearchResultsSimilarItem.vue
src/components/modules/SearchResultsTilesItem.vue
src/components/modules/collections/CollectionRecommendationsPanel.vue
src/components/modules/lists/ArticleItem.vue
src/components/modules/lists/ImageItem.vue
src/models/Page.js
src/pages/IssueViewerPage.vue
src/pages/Search.vue
src/router/index.js

- fix empty pages: safely get parameters of a possible undefined page (#986)
- fix thumbnail IIIF for BnL data

Release 2.7.1 IIIF patch

---

src/pages/Search.vue

Fix for https://github.com/impresso/impresso-frontend/issues/958

reset current page if we shoot out of bounds

---

src/components/modules/searchQueriesComparison/QueryHeaderPanel.vue
src/d3-modules/Timeline.js

Fix for https://github.com/impresso/impresso-frontend/issues/985 (fronend part). Depends on https://github.com/impresso/impresso-middle-layer/pull/300

use daterange filter in explorer

---

src/components/modules/SearchQuerySummary.vue

Fix for https://github.com/impresso/impresso-frontend/issues/989

parse dates only when we know it's a daterange filter

---

src/components/modules/OpenSeadragonArticleViewer.vue
src/pages/IssueViewerPage.vue

Viewer header optimizations

---

src/components/IssuePage.vue
src/components/modules/SearchResultsListItem.vue
src/components/modules/TableOfContents.vue

referring to issue #1004, 
`article.accessRight` returns 'na', even when the `article.issue.accessRights` is 'OpenPublic'
I assume that whenever issue is OpenPublic, all articles within the issue are OpenPublic too ... right ?

Public domain articles still require login #1004

---

src/App.vue
src/components/modules/CollectionAddToList.vue
src/components/modules/CollectionList.vue
src/components/modules/searchQueriesComparison/QueryHeaderPanel.vue

see issue #1005
@theorm is there a reason you left out these filters from supported types ?
they do seem to work fine, only the pills are not shown ...

added missing supported filter types

---

src/pages/UserRegister.vue

change message

---

src/assets/faqpage.json
src/components/base/InfoIgnoredFilters.vue
src/components/modules/searchQueriesComparison/FacetOverviewPanel.vue
src/components/modules/searchQueriesComparison/QueryHeaderPanel.vue
src/components/modules/searchQueriesComparison/SideBySideFacetsPanel.vue
src/i18n/messages.js
src/pages/SearchQueriesComparison.vue

fix #1095 add type to supportedFieldTypes and add info ignored component

---

package-lock.json
package.json
src/components/modules/searchQueriesComparison/QueryHeaderPanel.vue

patch v2.9.1 hotfix

---

package-lock.json
package.json
src/components/TopicsExplorerPage.vue

patch v2.9.2 hotfix topics page

---

package-lock.json
package.json
src/components/base/ImgAuthentified.vue
src/components/modules/lists/ImageItem.vue
src/pages/SearchImages.vue

* bump patch 2.9.3 hotfix
* remove test code for CORS
* add CORS friendly replacement to test conveniently in preproduction servers
* add login error message
fix #1120

v2.9.3 patch: Fix/issue 1120 image cors (#1122)

---

src/App.vue
src/components/TextReuseExplorerPage.vue
src/components/modules/Ellipsis.vue
src/components/modules/SearchQuerySummary.vue
src/pages/TextReuse.vue

fix #1203 (more /less button)
fix #1202

Fix UX text reuse issues

---

src/components/CollectionDetailPage.vue
src/components/EntitiesDetailPage.vue
src/components/EntitiesExplorerPage.vue
src/components/Explorer.vue
src/components/NewspapersDetailPage.vue
src/components/SelectionMonitor.vue
src/components/TextReuseClusterDetailPage.vue
src/components/TextReuseClusterIdCardPage.vue
src/components/TextReuseClusterMonitor.vue
src/components/TextReuseConnectedClusters.vue
src/components/TextReuseExplorerPage.vue
src/components/TextReusePassageMonitor.vue
src/components/TopicDetailPage.vue
src/components/modules/FilterDynamicRange.vue
src/components/modules/FilterFacet.vue
src/components/modules/collections/AddToCollection.vue
src/components/modules/collections/CollectionRecommendationsPanel.vue
src/components/modules/textReuse/TextReuseOverview.vue
src/pages/Search.vue
src/pages/SearchImages.vue
src/pages/SearchNgrams.vue
src/pages/SearchQueriesComparison.vue
src/pages/TextReuse.vue
src/pages/TextReuseClusters.vue
src/services/index.js
src/store/Collections.js
src/store/Entities.js
src/store/Search.js
src/store/SearchImages.js

See https://github.com/impresso/impresso-middle-layer/pull/393

Supporting query parameter and response changes made on the API side

---

.vscode/settings.json
src/components/modules/FilterFacet.vue
src/components/modules/FilterMonitor.vue
src/components/modules/FilterTimeline.vue
src/components/modules/Pagination.vue

pagination, filter monitor, filter facet

[chore] adding test ids for e2e tests

---

src/components/Autocomplete.vue
src/components/Explorer.vue
src/components/modules/FacetExplorer.vue

Issues identified while preparing e2e tests for the facet filter explorer.

Fixed open/close/submit issues in facet explorer

---

src/components/NewspapersLines.vue
src/pages/Newspapers.vue

Depends on changes in the IML: https://github.com/impresso/impresso-middle-layer/pull/398

[chore] Replaced filters query parameter in newspapers find with `includedOnly`.

---

src/components/SearchPills.vue
src/components/modules/FilterMonitor.vue
src/components/modules/lists/ItemLabel.vue
src/components/stories/SearchPills.stories.ts

Various small fixes of problems discovered when navigating deep links from `impresso-py` results.

[FIX] Various fixes

---

src/components/modules/AnnotatedText.vue
src/components/modules/IssueViewerText.vue
src/components/modules/stories/AnnotatedText.stories.ts
src/router/index.ts

Fixes https://github.com/impresso/impresso-frontend/issues/1259

[chore] Refactor and fix text reuse view

---

src/components/SelectionMonitor.vue
src/components/legacy/bootstrap/BFormCheckbox.vue
src/components/modules/ItemSelector.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1272

issue 1272

---

.vscode/launch.json
.vscode/tasks.json
src/components/modules/FilterMonitor.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1293

replace items in array instead of replacing the whole array

---

src/components/TheHeader.vue
src/components/legacy/bootstrap/BNavItemDropdown.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1291

[issue-1291] fix dropdowns

---

src/components/base/DatepickerButton.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1292

[issue-1292] enable model update

---

src/components/Monitor.vue
src/components/modules/ItemSelector.vue
src/components/modules/searchQueriesComparison/SideBySideFacetsPanel.vue
src/pages/SearchQueriesComparison.vue
src/stores/monitor.ts

Fixes https://github.com/impresso/impresso-frontend/issues/1299

[issue-1299] Fixed filter update errors

---

src/components/TextReuseClusterMonitor.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1303

[issue-1303] watch orderby changes

---

src/components/TextReuseClusterMonitor.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1302

[issue-1302] Watch text reuse cluster monitor parameters changes

---

.vscode/settings.json
src/components/modules/CollectionList.vue
src/stores/collections.ts

Fixes https://github.com/impresso/impresso-frontend/issues/1287

[issue-1287] fixed collections sorting

---

package-lock.json
package.json
src/components/NewspapersExplorerPage.vue
src/components/base/InfoButton.vue
src/styles/style.css

Fix InfoButton Popover style and placement

---

src/pages/SearchNgrams.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1266

[issue-1266] allowed collections

---

src/assets/faqpage.json
src/components/TheHeader.vue
src/services/index.ts
src/services/types.ts
src/stores/notifications.ts

Improved error capture

---

src/assets/faqpage.json
src/components/TheHeader.vue
src/services/index.ts
src/services/types.ts
src/stores/notifications.ts

* app error capture code updated

Release v3.0.2

---

.vscode/tasks.json
package.json
src/components/CollectionDetailPage.vue
src/components/modules/lists/ArticleItem.vue
src/components/modules/lists/ImageItem.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1333

fixed empty uid error

---

src/components/modules/searchQueriesComparison/SideBySideFacetsPanel.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1337

null checking

---

src/components/Explorer.vue
src/components/base/Modal.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1366

fixed tab header

---

src/components/modules/searchQueriesComparison/DivergingBarsChartPanel.vue
src/components/modules/vis/DivergingBarsChart.vue
src/d3-modules/DivergingBarsChart.js

Fixes https://github.com/impresso/impresso-frontend/issues/1367

fixed tooltip

---

src/i18n/messages.js

Fixes https://github.com/impresso/impresso-frontend/issues/1384

Rename "update password" button

---

src/components/Monitor.vue
src/stores/monitor.ts

Fixes https://github.com/impresso/impresso-frontend/issues/1394 and https://github.com/impresso/impresso-frontend/issues/1393

Hide json displayed instead of wikidata entry, removed use of undeclared local variable

---

src/components/Monitor.vue
src/pages/SearchQueriesComparison.vue
src/stores/monitor.ts

Fixes https://github.com/impresso/impresso-frontend/issues/1396

Use most recent query 

---

src/components/base/InfoButton.vue
src/components/modules/searchQueriesComparison/DivergingBarsChartPanel.vue
src/components/modules/searchQueriesComparison/QueryHeaderPanel.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1406
Fixes https://github.com/impresso/impresso-frontend/issues/1407
Fixes https://github.com/impresso/impresso-frontend/issues/1409
Fixes https://github.com/impresso/impresso-frontend/issues/1410

fixed various UI issues

---

src/components/modules/SearchResultsImageItem.vue
src/components/modules/lists/ImageItem.vue
src/models/index.d.ts
src/pages/IssueViewerPage.vue
src/pages/SearchImages.vue
src/services/index.ts
src/stores/issue.ts

Support new image service. See https://github.com/impresso/impresso-middle-layer/pull/492

New image service support

---

src/components/modules/searchQueriesComparison/QueryHeaderPanel.vue

See https://github.com/impresso/impresso-middle-layer/pull/503 and https://github.com/impresso/impresso-frontend/issues/1433

allowed supported filters in I&C

---

src/pages/Search.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1415

hide not allowed filters

---

src/components/base/DatepickerButton.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1450

Focus and close datepicker in Safari

---

src/pages/Search.vue
src/pages/SearchImages.vue

Release v3.1.3

---

src/components/modules/EmbeddingsSearch.vue
src/services/types/embeddings.ts
src/services/types/images.ts
src/services/types/index.ts
src/stores/embeddings.ts

Supporting new embedding service https://github.com/impresso/impresso-middle-layer/pull/526

updated embeddings search component

---

src/components/modules/lists/ItemLabel.vue
src/models/Bucket.js
src/models/Partner.ts
src/pages/Search.vue

For https://github.com/impresso/impresso-middle-layer/pull/529

loading facet details for partner facet

---

package-lock.json
package.json

[chore] Bump impresso jscommons

---

.storybook/mswHandlers.ts
package-lock.json
package.json
src/components/TextReuseExplorerPage.vue
src/components/base/Modal.vue
src/components/modules/datalab/CopyToDatalabButton.stories.ts
src/components/modules/datalab/CopyToDatalabButton.vue
src/components/modules/datalab/CopyToDatalabPanel.stories.ts
src/components/modules/datalab/CopyToDatalabPanel.vue
src/pages/Search.vue
src/services/index.ts
src/services/types/datalabSupport.ts
src/services/types/index.ts
src/stores/settings.ts

Requires https://github.com/impresso/impresso-middle-layer/pull/533

A "copy to datalab" button and modal

---

.github/copilot-instructions.md
src/components/modules/filters/FilterTextInput.stories.ts
src/components/modules/filters/FilterTextInput.vue
src/components/modules/filters/FiltersRenderPanel.stories.ts
src/components/modules/filters/FiltersRenderPanel.vue
src/pages/FilterParserPage.stories.ts
src/pages/FilterParserPage.vue
src/router/index.ts

Quickly parse a base64 filter string or a URL that contains a filter

Parse filters helper page

---

package-lock.json
package.json
src/components/modules/filters/FilterJsonInput.stories.ts
src/components/modules/filters/FilterJsonInput.vue
src/components/modules/filters/FilterTextInput.vue
src/components/modules/filters/FilterUrlPanel.stories.ts
src/components/modules/filters/FilterUrlPanel.vue
src/components/modules/filters/FiltersRenderPanel.stories.ts
src/components/modules/filters/FiltersRenderPanel.vue
src/pages/FilterParserPage.stories.ts
src/pages/FilterParserPage.vue

* updated filter helpers page to allow editing filters
* jscommons version bump

Filter helper page updates

---

src/components/modules/WikidataBlock.vue
src/components/modules/lists/EntityItem.vue
src/i18n/messages.js
src/models/Entity.js

https://github.com/impresso/impresso-middle-layer/pull/536

New entities format support

---

src/components/AcceptTermsOfUse.vue

add translations and link to ToU modal

---

src/widget/views/StaticImage.vue

Related to https://github.com/impresso/impresso-middle-layer/issues/532

made static image url iiif v3 compatible

---

src/pages/Search.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1565

removed duplicate partner facet

---

src/components/Autocomplete.vue
src/components/Explorer.vue
src/components/HomePage2020.vue
src/components/IIIFFragment.stories.ts
src/components/base/Icon.vue
src/components/base/Modal.vue
src/composables/useClickOutside.ts
src/styles/style.css

Will fix #1549 and improve search input autocomplete

simplify dark mode

---

package-lock.json
package.json
src/components/SearchPills.vue
src/components/base/Icon.stories.ts
src/components/base/Icon.vue
src/components/modules/SearchSidebar.vue
src/i18n/messages.js
src/logic/filters.js
src/models/Bucket.ts
src/models/Facet.ts
src/pages/Search.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1633

added new filter types

---

src/components/modules/searchQueriesComparison/FacetOverviewPanel.vue
src/components/modules/searchQueriesComparison/SideBySideFacetsPanel.vue
src/components/modules/searchQueriesComparison/stories/FacetOverviewPanel.stories.ts
src/pages/SearchQueriesComparison.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1660

Fixed percentage mode

---

src/pages/SearchQueriesComparison.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1661

Getting all values for the "year" facet

---

src/components/IIIFFragment.vue
src/components/modules/SearchResultsListItem.vue

Partially addresses https://github.com/impresso/impresso-frontend/issues/1673

clamp down out of bounds coordinates

---

src/pages/Search.vue

https://github.com/impresso/impresso-frontend/issues/1668

Brought back the save to collection / export csv button.

---

src/components/modules/FilterRange.vue
src/components/modules/vis/HistogramSlider.stories.ts
src/components/modules/vis/HistogramSlider.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1676

added tooltip in HistogramSlider

---

src/components/CollectionDetailPage.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1669

hidden recommendations tab

---

src/components/CollectionDetailPage.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1667

fixed buckets initialization

---

src/components/NewspapersDetailPage.vue
src/components/modules/MetadataTable.stories.js
src/components/modules/MetadataTable.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1547

collapsible metadata table

---

src/i18n/messages.js
src/pages/Search.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1641

Use OCR quality as the default order by value

---

src/components/modules/lists/DataProviderLabel.vue
src/init.ts
src/models/ImpressoMetadata.ts
src/services/index.ts
src/services/local/dataProviders.ts

Needs https://github.com/impresso/impresso-middle-layer/pull/602

added data providers service

---

src/components/modules/textReuse/TextReuseOverview.vue
src/logic/filters.js
src/pages/SearchQueriesComparison.vue
src/pages/TextReuse.vue

Fixes https://github.com/impresso/impresso-frontend/issues/1744

added nag and organisation facets to TR page and I&C page

---

src/pages/Search.vue

Introduces a separate timelineFacets array to handle the 'year' facet independently from other facets. Updates computed facets to include timelineFacets and loads 'year' facet data on search. This refactor supports timeline-specific filtering and improves facet management and fix #1737

Add timelineFacets for 'year' facet in Search page
